test arrays
Nblyumenshteyn/study pull request #1
Opened 2021-04-13 18:50 UTC by Nblyumenshteyn

2021-04-14 10:12 UTC, Andrew8xx8 requested changes

2021-04-14 10:12 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        new_max = -1
В данном случае этот код будет работать, но в общем случае максимум так не стоит искать, что если массив целиком из отрицательных чисел меньше -1? Следует это поправить.

Так же поиск максимума нужно вынести в отдельный метод

2021-04-14 18:27 UTC, Nblyumenshteyn commented on test/exercise/arrays/solution.rb
> +        new_max = -1
Поправила

2021-04-19 10:27 UTC, Andrew8xx8 commented
Лишние файлы `.DS_Store`, их необходимо удалить из коммита и добавить в `.gitignore`, чтобы они игнорировались гитом

2021-04-19 10:59 UTC, Andrew8xx8 requested changes

2021-04-19 10:59 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        max_val = lambda { |arr, new_m|
Зачем здесь лямбда? Можно же просто `array.each` вызвать?

2021-04-19 10:59 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        return unless array.length.positive?
А зачем проверять, что длинна положительное число? Если надо проверить, что массив не пустой, или пустой, нужно так и написать `array.empty?`

2021-04-19 10:59 UTC, Andrew8xx8 requested changes

2021-04-19 10:59 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +          if arr.length.positive?
Тут тоже самое, что и выше

2021-04-19 21:24 UTC, Nblyumenshteyn commented on test/exercise/arrays/solution.rb
> +          if arr.length.positive?
Поправила, в fix arrays  и fix arrays2

2021-06-29 09:58 UTC, Andrew8xx8 approved these changes

2021-07-01 18:41 UTC, merged